<?php

namespace AppBundle\Repository;

/**
 * productionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productionRepository extends \Doctrine\ORM\EntityRepository
{
}
